# Generated by Django 3.2.8 on 2021-10-07 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
